"""Initial migration for Employee table

Revision ID: 47eba6be2acd
Revises: 
Create Date: 2024-11-24 18:47:59.393710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47eba6be2acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
